kodiri/drink-me-app

- src/App.js
> changed ! test

- package-lock.json
- src/App.js
> Update text and add package-lock.json

- package-lock.json
- package.json
- public/index.html
- src/App.js
- src/Components/Drink/Drink.css
- src/Components/Drink/Drink.js
- src/Components/Results/Results.css
- src/Components/Results/Results.js
HI, I have added the Drink and Results component
> Add Drink and Results components

- package-lock.json
- src/Components/NavBar/NavBar.css
- src/Components/NavBar/NavBar.js
- src/Components/NavBar/NavBar.svg
- src/Components/Team/Team.css
Navbar is now mobile responsive
> navbar mobile responsive

- src/App.css
- src/Components/Main/Main.css
- src/Components/NavBar/NavBar.css
> improving the Ui of the App

- src/Components/NavBar/NavBar.css
> fixing the NavBar

- package-lock.json
- package.json
- src/Components/Main/Main.css
- src/Components/NavBar/NavBar.css
- src/Components/NavBar/NavBar.js
- src/Components/Team/Team.css
I have fixed the issues with the navbar
> Improve NavBar component

- src/Components/NavBar/NavBar.css
> updating NavBar

- package-lock.json
- package.json
update package.json to prepare it to deploy in heroku
> Update package.json file

- src/App.js
- src/Components/Drink/Drink.js
- src/Components/Main/Main.css
- src/Components/Main/Main.js
- src/Components/Page/Page.js
- src/Components/Results/Results.js
- src/TeamMember/TeamMember.js
We all added the API functionality but we are still getting errors that need to be fixed.
> Add APIS functionality

- src/Components/Main/Main.css
- src/Components/Main/Main.js
- src/Components/Page/Page.js
- src/Components/Results/Results.js
> Fix issue with url in the Results component

- src/Components/Main/Main.js
- src/Components/Random/Random.js
- src/Components/Random/RandomResults.js
> adding the random Api

- src/Components/Drink/Drink.js
- src/Components/Main/Main.js
Hi, I have fixed the issue with the second call to the API. We were calling it with ingredient="" so I have updated the code and the Results component will only be rendered once the ingredient has been selected
> fix issue with the second call to the API on the Results page

- src/Components/NavBar/NavBar.js
- src/Components/Results/Results.js
> updated fork

- package-lock.json
- package.json
- src/Components/Main/Main.css
- src/Components/Main/Main.js
- src/Components/NavBar/NavBar.css
- src/Components/NavBar/NavBar.js
- src/Components/Team/Team.js
> navbar routing complete

- src/Components/Main/Main.css
- src/Components/NavBar/NavBar.css
- src/Components/Results/Results.css
- src/Components/Team/Team.css
- src/TeamMember/TeamMember.css
> UI of Main.js update

- src/Components/NavBar/NavBar.css
remove curly brace form NavBar
> remove curle brace from NavBar

- public/index.html
- src/App.js
- src/Components/Detail/Detail.css
- src/Components/Detail/Detail.js
- src/Components/Drink/Drink.css
- src/Components/Results/Results.css
- src/Components/Results/Results.js
Render the list of ingredients in the Details component and improve styles
> Render the list of ingredients in the Details component and improve styles

- src/Components/Detail/Detail.css
- src/Components/Detail/Detail.js
- src/Components/Drink/Drink.css
- src/Components/Results/Results.css
Fix typo in Detail component and improve Results component for small screens
> Fix typo in className and improve Results component styles

- src/Components/Results/Results.js
> remove drink with id=17246

- src/Components/Main/Main.css
- src/Components/Main/Main.js
Add random API Details recipe and UI mobile and devices for Main page
> Add random API Details recipe and UI mobile and devices for Main page

- src/App.js
- src/Components/Detail/Detail.js
- src/Components/Drink/Drink.js
- src/Components/Results/Results.js
Update url for the details component to display name instead of id
> Update url for the details component to display name instead of id

- src/App.css
- src/Components/NavBar/NavBar.css
Remove overflow from App.css because it was cropping the components
> Remove overflow from App.css because it was cropping the components

- src/Components/Team/Team.css
- src/Components/Team/Team.js
- src/TeamMember/TeamMember.js
> email added

- src/App.css
- src/Components/Main/Main.css
- src/Components/NavBar/NavBar.css
- src/TeamMember/TeamMember.css
> fix the NavBar issues

- src/Components/NavBar/NavBar.css
- src/Components/NavBar/NavBar.js
- src/Components/Page/Page.js
- src/Components/Team/Team.js
- src/TeamMember/TeamMember.css
- src/TeamMember/TeamMember.js
bug fixing navbar & added in portfolio icon/link
> bug fixing navbar & added in portfolio icon/link

- src/App.js
- src/Components/Drink/Drink.js
- src/Components/Main/Main.css
- src/Components/Main/Main.js
- src/Components/Page/ButtonUp/ButtonUp.css
- src/Components/Page/ButtonUp/ButtonUp.js
- src/Components/Page/Page.js
- src/ScrollTop/ScrollTop.js
- src/index.css
Hey guys,
I added UseHistory Hooks for ScrollTop Page and Button Up for better UI of the App
> Add UseHistory Hooks for ScrollTop and Button Up

- src/Components/Main/Main.css
- src/Components/Main/Main.js
- src/Components/Page/ButtonUp/ButtonUp.css
- src/Components/Page/ButtonUp/ButtonUp.js
> updating the API id-drinks

- src/Components/NavBar/NavBar.css
- src/Components/NavBar/NavBar.js
- src/TeamMember/TeamMember.css
- src/TeamMember/TeamMember.js
> team pictures reduced size

- src/Components/Main/Main.css
> Add full width Main

- package-lock.json
- package.json
- src/Components/Drink/Drink.css
- src/Components/Drink/Drink.js
- src/Components/Random/Random.css
- src/Components/Random/Random.js
- src/Components/Results/Results.css
- src/Components/Results/Results.js
Work on UI Random component and add animations to resuls
> Work on UI Random component and add animations to resuls

- src/App.css
- src/Components/Main/Main.css
- src/Components/Main/Main.js
- src/Components/MainText/MainText.css
- src/Components/MainText/MainText.js
- src/Components/Random/Random.css
- src/Components/Results/Results.css
Fix problem with padding on small screens and reduce text main page
> Fix problem with padding on small screens and reduce text main page

- src/Components/NavBar/NavBar.css
- src/Components/Random/Random.css
- src/Components/Random/Random.js
- src/Components/Results/Results.css
Navbar hover added and random styles improved
> Navbar hover added and random styles improved

- src/Components/Detail/Detail.css
- src/Components/Drink/Drink.css
- src/Components/Drink/Drink.js
- src/Components/Random/Random.css
- src/Components/Random/Random.js
- src/Components/Results/Results.css
- src/Components/Results/Results.js
Refactor code Detail, Drink, Random and Results
> Refactor code Detail, Drink, Random and Results

- src/Components/Main/Main.css
- src/Components/Main/Main.js
- src/TeamMember/TeamMember.css
> Add UI changes

- src/Components/Main/Main.css
- src/Components/Main/Main.js
- src/Components/MainText/MainText.js
Improve CSS for Main and Maintext
> Improve CSS for Main and Maintext

- src/Components/Main/Main.js
- src/Components/Random/Random.css
- src/Components/Random/Random.js
- src/Components/Results/Results.js
Remove console error in form, fix flashing random image and add scroll to results
> Remove console error in form, fix flashing random image and add scroll to results

- src/Components/Main/Main.css
Fix buttons on Safari and Chrome
> Fix buttons on Safari and Chrome

- src/Components/Main/Main.css
> Fix mobile UI
